### ISSUE TITLE
希望增加pnpm切源

### ISSUE THREAD

**Issue by guohui666** [daysai/cgr#10]
希望增加pnpm切源

**Comment by daysai** [comment]
计划增加中，但会增加开关配置，默认关闭 pnpm，以免干扰没有使用 pnpm 的用户

**Comment by daysai** [comment]
cgr@1.4.0 版本增加 pnpm 切源功能，需要开启 pnpm ，默认关闭
<img width="816" alt="image" src="https://user-images.githubusercontent.com/18555391/188266255-120b1152-858e-40f4-9f96-161bcbe37bef.png">
