### ISSUE TITLE
This does not seem to support Windows PowerShell. . .

### ISSUE THREAD

**Issue by rxliuli** [daysai/cgr#3]
![image](https://user-images.githubusercontent.com/24560368/71158404-d6038500-227e-11ea-8336-55dc90e8fd1d.png)

**Comment by daysai** [comment]
fixed in cgr@1.2.7, thanks!

**Comment by rxliuli** [comment]
I have changed to yrm...

**Comment by daysai** [comment]
> I have changed to yrm...

Sorry for missing, still thanks for feedback
