### ISSUE TITLE
some bugger in win10 using cgr

### ISSUE THREAD

**Issue by Zhantrywei** [daysai/cgr#4]
Q1: powershell use cgr error
A1: run powershell with admin and get-ExecutionPolicy, if get-ExecutionPolicy=>Restricted,please set-ExecutionPolicy RemoteSigned and all yes.
Q2: cmd or powershell use cgr ls showing process.env.HOME undefined,causing path.join error
A2: add HOME => your username dir in system variable

**Comment by daysai** [comment]
`const HOME = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;`
fixed in cgr@1.2.7, thanks!
