### ISSUE TITLE
换行符错误

### ISSUE THREAD

**Issue by Bit0r** [daysai/cgr#5]
新版cgr在使用时会出现报错，其原因是使用了\r\n换行。这在Linux上这导致了错误，请求修正
```
/usr/bin/env: ‘node\r’: No such file or directory
```

**Comment by daysai** [comment]
能否提供一下错误信息截图，新版本并未增加换行符改动。只修改了 window 系统下的环境变量问题

**Comment by daysai** [comment]
> 新版cgr在使用时会出现报错，其原因是使用了\r\n换行。这在Linux上这导致了错误，请求修正
> 
> ```
> /usr/bin/env: ‘node\r’: No such file or directory
> ```
能否提供一下错误信息截图，新版本并未增加换行符改动。只修改了 window 系统下的环境变量问题

**Comment by Bit0r** [comment]
错误信息就是这个
```
/usr/bin/env: ‘node\r’: No such file or directory
```
我的系统：
KUbuntu 20.04

**Comment by Bit0r** [comment]
我怀疑是上游错误，因为我使用了dos2unix，但是没有发现CRLF换行符

**Comment by Bit0r** [comment]
我在`~/.config/yarn/global/node_modules/cgr`下运行了`dos2unix`，这个错误就消失了。
看起来是npm源上的cgr有CRLF

**Comment by daysai** [comment]
> 我在`~/.config/yarn/global/node_modules/cgr`下运行了`dos2unix`，这个错误就消失了。
> 看起来是npm源上的cgr有CRLF

可是尝试一下使用原生npm的命令设置源方式是否有报错信息：npm config set registry https://registry.npm.taobao.org/ 
cgr 只会对根目录下的 .cgrrc 文件进行读写操作，其余都是直接使用npm/yarn原生命令操作切源。

**Comment by Bit0r** [comment]
我的意思是npm源里的`cli.js`文件是CRLF格式的换行，而github项目里的`cli.js`是LF的换行

**Comment by daysai** [comment]
> 我的意思是npm源里的`cli.js`文件是CRLF格式的换行，而github项目里的`cli.js`是LF的换行

是否有兴趣提个 mr 修复一下？或者有什么修复建议？

**Comment by Bit0r** [comment]
项目里的是对的，没有'\r'

**Comment by Bit0r** [comment]
但是你push到npm里的时候可能是什么工具把项目里的文件修改了

**Comment by daysai** [comment]
> 但是你push到npm里的时候可能是什么工具把项目里的文件修改了
看起来可能和 Linux 解析默认文件的方式有关

**Comment by Bit0r** [comment]
看起来这个事情没有解决办法，我关闭issue了。

**Comment by greatpie** [comment]
我在macos下也遇到了这个问题，是否可以更新一下npm源，github仓库的换行符确实没问题。

**Comment by daysai** [comment]
> 我在macos下也遇到了这个问题，是否可以更新一下npm源，github仓库的换行符确实没问题。

麻烦提供下报错信息、系统环境、cgr 版本

**Comment by daysai** [comment]
> 我在macos下也遇到了这个问题，是否可以更新一下npm源，github仓库的换行符确实没问题。

已经更新 1.2.8 ，增加 .gitattributes 文件尝试调整为 LF。

**Comment by daysai** [comment]
> 看起来这个事情没有解决办法，我关闭issue了。

已经更新 1.2.8 ，经过 mac 重新发布。增加 .gitattributes 文件尝试调整为 LF。
