### ISSUE TITLE
关于新增镜像

### ISSUE THREAD

**Issue by Hb-zzZ** [daysai/cgr#6]
1. 这边在C盘特定目录新增了镜像后，再次新增会出现下图错误
![Snipaste_2020-12-11_18-36-56](https://user-images.githubusercontent.com/31434560/101893636-f7702600-3bdf-11eb-88cc-3c09b73c8750.jpg)

2.在C盘目录新增成功后，CMD切到F盘的路径下，此时新增的镜像消失
![Snipaste_2020-12-11_18-40-17](https://user-images.githubusercontent.com/31434560/101893875-55047280-3be0-11eb-86b8-e376c25cf468.jpg)

这边建议搞一个config命令，把.cgrrc路径做成配置，这样每个路径都能访问，作者大大加油!

**Comment by Hb-zzZ** [comment]
close

**Comment by daysai** [comment]
问题 close 的原因是解决了？

**Comment by Hb-zzZ** [comment]
还是存在这些问题

**Comment by daysai** [comment]
这个问题可以尝试解决下，暂时没想到什么好方法，从描述上，配置式也不能直接跨盘？或者也可以看下nrm之类的解决方案

**Comment by Hb-zzZ** [comment]
建议尝试把读取HOME的路径改成 os.homedir()

**Comment by daysai** [comment]
> 建议尝试把读取HOME的路径改成 os.homedir()

更新了 1.2.9 版本，改成了 os.homedir()
